### ISSUE TITLE
The link for downloading scRNAseq data (10x and SORT-seq) in README is broken

### ISSUE THREAD

**Issue by yuqiyuqitan** [anna-alemany/mouseGastruloids_scRNAseq_tomoseq#1]
Hi,

Thanks for sharing the scripts and the data, but the link for downloading scRNAseq data (10x and SORT-seq) in README is broken. Since it is really difficult to figure out which processed data belongs to which experiment in GEO, would you mind repairing the link so that users can download the count matrix directly from the repo? 

Thank you very much,
Best
Yuqi

**Comment by anna-alemany** [comment]
Dear Yuqi, 

Thanks for calling my attention on this issue. You can find a link to the raw data here: 
https://www.dropbox.com/sh/pxuas7bd34zzc3t/AACbCqEXq1qVffh7x75Y59NGa?dl=0

Cheers, 
Anna
