### ISSUE TITLE
Reproducible cluster annotation

### ISSUE THREAD

**Issue by yuqiyuqitan** [anna-alemany/mouseGastruloids_scRNAseq_tomoseq#2]
Hi,

Thanks again for sharing your raw data and the scripts. I was able to follow both transcriptome_scanpy_10xSORT.py and cellcluster_annotation.py to completion without any errors. However, the final clustering result does not seem to be the same as Figure 1 in the paper. Would you mind sharing the original metadata of this analysis?

[umap_celltype_option1.pdf](https://github.com/anna-alemany/mouseGastruloids_scRNAseq_tomoseq/files/5284410/umap_celltype_option1.pdf)

Thank you so much,
Best
Yuqi

sc.logging.print_versions()
scanpy==1.4.6 anndata==0.7.4 umap==0.4.6 numpy==1.17.0 scipy==1.5.2 pandas==1.1.1 scikit-learn==0.23.2 statsmodels==0.11.1

**Comment by anna-alemany** [comment]
Dear Yuqi, 

Thanks for your message. I will have a look at this in the upcoming days and come back to you asap. 

Cheers, 
Anna

**Comment by yuqiyuqitan** [comment]
Hi Anna,

I just want to follow up to see if you had a chance to look into this and is willing to share with me the metadata?

Thanks,
Yuqi

**Comment by anna-alemany** [comment]
Dear Yuqi, 

The input raw data can be found here: https://www.dropbox.com/sh/pxuas7bd34zzc3t/AACbCqEXq1qVffh7x75Y59NGa?dl=0 

This is the scanpy object that I get is here: https://www.dropbox.com/s/f2kgd38ps0qktrn/adata_clusters.h5ad?dl=0

The final metadata can be found in the supplementary table 1 of the original paper: https://www.nature.com/articles/s41586-020-2024-3#Sec32 (you have the umap coordinates and the final cluster assignment, which was obtaiend by combination of leiden and kmedoids results)

The final cell type annotation can also be found here: https://avolab.hubrecht.eu/MouseGastruloids2020/

Does this help? 

Cheers, 
Anna

**Comment by yuqiyuqitan** [comment]
Hi Anna,

Thank you so much for your prompt reply! You are of tremendous help! I am finally able to reconstruct the adata.

Thanks again,
Have a lovely day,
Yuqi
