### ISSUE TITLE
shiny server Gastruloid scRNAseq

### ISSUE THREAD

**Issue by deWitLab** [anna-alemany/mouseGastruloids_scRNAseq_tomoseq#3]
I am not sure if this is the correct place to post this, but there seem to be some issues with the website you built to browse the gastruloid scRNAseq data. It does not seem to generate UMAP plots anymore and the gene selection is now via a drop-down menu. The website was very useful to us, so it is unfortunate it stopped working.

**Comment by anna-alemany** [comment]
Thanks for your message. I checked the website and it seems to be working here. When I click on the genes in the tables, the expression of the UMAP and the TomoSeq data is displayed. When I start typing the name of the gene, then the drop-down menu shows me the options. When did your issues start?

**Comment by deWitLab** [comment]
Sorry, about that. I checked it with Chrome and it is okay. However, with the newest Safari on Catalina it does not work. Perhaps this is because of the out-of-date security certificate.
